---
- name: Create directory for Qt installer files
  file:
    path: "{{toolsdir}}/download_cache"
    state: directory

- name: Create directory for Qt installer script file
  file:
    path: /var/lib/ansible/qt
    state: directory
    owner: vagrant
    group: vagrant
  become: true

- name: Download Qt
  get_url:
    url: https://download.qt.io/official_releases/qt/5.10/5.10.1/qt-opensource-linux-x64-5.10.1.run
    dest: "{{toolsdir}}/download_cache/qt-opensource-linux-x64-5.10.1.run"
    mode: 0550

- name: Copy Qt installer script
  template:
    src: script.qs
    dest: /var/lib/ansible/qt
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Install Qt
  shell: "{{toolsdir}}/download_cache/qt-opensource-linux-x64-5.10.1.run --platform minimal --script /var/lib/ansible/qt/script.qs"
  args:
    creates: "{{toolsdir}}/qt/5.10.1/"

# This can hopefully be removed for future Qt versions.
- name: Make sure that the Qt Maintenance Tool has a repository available
  copy:
    src: qt-maintenance-network.xml
    dest: "{{toolsdir}}/qt/network.xml"

- name: Install mesa development headers (for Qt gui development)
  apt: name={{item}} state=present
  with_items:
    - mesa-common-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev # necessary for Raspberry Pi cross compiling
  become: true

- lineinfile:
    destfile: "{{homedir}}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    line: '[Containments][2][Applets][3][Configuration][General]'

- name: Set the favorites for the start menu
  lineinfile:
    destfile: "{{homedir}}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    insertafter: '^[Containments][2][Applets][3][Configuration][General]'
    regexp: '^favorites=preferred://.*'
    line: 'favorites=preferred://browser,org.kde.dolphin.desktop,org.kde.kate.desktop,DigiaQt-qtcreator-community.desktop,systemsettings.desktop'

- lineinfile:
    destfile: "{{homedir}}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    line: '[Containments][2][Applets][5][Configuration][General]'

- name: Add launcher for the QtCreator
  lineinfile:
    destfile: "{{homedir}}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    regexp: '^launchers=.*qtcreator'
    insertafter: '^[Containments][2][Applets][5][Configuration][General]'
    line: "launchers=file:///usr/share/applications/org.kde.dolphin.desktop,file://{{homedir}}/.local/share/applications/DigiaQt-qtcreator-community.desktop?iconData=iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAS8klEQVR4nO2de3Qc1X3Hv3dmdyXtStrVrrSrhyVLluSHsI0NfmAEwcKEgh6WS8Ckpw2FhnNKegJp0tMSmubUcNLAyYGEpCdNCaEJbUJzSOK2SAgHGwuTYGRLNtgWfmBLtizL1urh1Wq175m5_WO9a1meGe1qR_LIvp9zdOzZ38y9d_b3vY_53XtnAQaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGPMJci0yvfvAA9so8M_XIu_rjfZbt6flQ06rgiQLc76-mFMBMOfrjzkTAHO-PpkTATDn65dZFwBzvr6ZVQEw5-ufWRMAc_78YFYEwJw_f9BcAMz58wtNBcCcP__QTADM-fMTTQTAnD9_MaSbwLVwfnlmKVZk12CxeRGKMlwoMDqQwZmQxWdCpBKCYhDjog9DkRH0hc7hmP8kDk18ioAYnMtizgvSFsBcOd_MZ2Fz_p_gPsfdKMssUT3XZshFEVxYYq7CnZc-C0sRdIwfwG_cLTjqPzH7BZ4npC2AueA-Rx2-UvIocgzZM04jgzPhLtsG3GXbgA-9-_Hy2Z9iNOqZUVq7b_mdou3ug1-YaRGvCXM-HZwKBsLjm-VP4h8WfjUt50-l1roOry57CUvMlZqlGYdcmyUWM0a3AiAgeKb8a7jXvnFW0rcZrHipehsqsso0TZcjuv1KZdFtaR9yNaEur3ZW8zDzZjy36GlkchmapTnfWgBdjgGKTE48VvRF1XMoKD72deMPYx04MnEMY4IXY8I4TMSIPKMNxSYXNljX4M6821BgdCimU5JRiEeKtuKnA_-lSdk5QgCqSVJzgi4F8EjRw8hQqZU9wTN4_syP0Bvsu8oWomFcCLtxIezGAd9h_PvA69jqasZjRV8ET3jZ9B4oaMBvh1pwMTqWdtmJfhtVWXRX2gKjA5vsdyraj_lP4qkT35J1vhwCFfHG4Hb8y5mXQRWqpokz4k8L6mdU3qlw86wL0J0A7nF8DgaFmhqSwnju9EsISqGU033fsxctw-8q2j9vv0uT_puQ-SUA3XUBagO_d0ffhzsyPOO033BvR0P-PbJdgdOUjxrLYnw6JUik9swvx6-Xv3JFS5PNW64Q1oNHvqxJV6MVumoBbAYrKrPKZW0UFP8z3JZW-kOREXzo7VS0r8ldlVb6QMzhOXx24m9qqyJSKe08tERXAlievVSxGT4bGkBf6FzaeXw4tk81_9lGAhOAIuWZCxRthyc-1SSPwxPHFG3TzTFogcRaAGVKVQTQPXFckzzckWEMR0dlbflGO8x8lib5KKH0JHKt0JUA1FqA_vAFzfIZCMmnRUBQmlGsWT5y6G0MoKungAWZyl9-OqP_q9MaUS3DiUBP4lhudk_tyaD50F8iJIURpdH0CjlH6EYABmJAFpcpawtLEYxFvZrlNaQiphw-vVlHnziR1vVzjW66gCxe3vkAMCFOaNp3jqs4ScuJofmAfgSgUPuBWAugJRFJuXnOVCnH9ciNKQAaVi6HSkt0PaIbAag1vRGNB1RqglIT4vWIbgSgFiHTeoaNU7ltqrNI3WyjGwEEReVm2cSZNM1LLb2IJGial97RjQBCKlO8JmLUNC8Tp5xehGo73tA7OhLAHLYARK0FmB8BHK3QkQCUWwCrIVfT1bY2Q66izSuMa5bPfEA3kUCBivCJE7KROAPhkWewzngjx1QcRruibUzQLuKoZ9ra2jJEUazQTQsAAOcUJmmA2EydVuSb1ARw_bcAbW1tCyilv-F5_ry-BKAy41eY4dIsH5epQNHmDg9plo8eeeutt-6SJKmLUtpaX18_risBDITPK9qWmqs0ySObt6Ako1DWFpYiGExz1lGvO4Pa29sNLS0t2ziOew_AiMVi-Q9AR2MAAOgPqQjAoo0AlliqFJedDYQvJDXpJFBRceVyJpehu23obW1tlX6__3VCSC0AcBz393V1dQKgo6cAADjuP6loW2qu0iRMu9KyTDn_wKmk0girPLLqKZS8bds2rqWl5WuSJB0BEF9uvau-vv6d-Dm6EsCFyBCGFBZrZHAZqhtGkoGA4F7HRkX7x74jSaWj9siaa8hJtVizQktLyy1r1qz5IyHkZQDxdW4SpfTpyefpSgAAsG_8gKKtueC-tPrYDdY1igNAkYo4mKQALqosTtFqrDJTWltb81paWn5ICNkPYMMU8y-ampoOTv5AdwJo93yoaKvMKsejRQ_PKF2HMQ9PlT6uaP_Q2wlPkhs2-sMDiraNebXXZIdwS0uLubW19WkAPYSQpwgh_JRdShFK6bNTr9PVIBAADvmOoi90DgsVFoj-ReGDyOKy8LPzv1Ltiyez2FyJb1d8A05TvuI5vxtqTbqMvcE-3J13h6xtbe4qvFbzAxz3n4RARVh4M0ycEZlcJrK4TDx54h81Xd3U1dVlHBwcfAyxV_UUE0Jgt9shiiL8fj8EQQClFAB-3tTUdHbq9boTAAXFG4Pb8Uz5U4rnfMHZgI15G7Dr4h-w19uJ4_5TVy3CtBttWJu7CrXW9ai1rVWtlXs8e3FEZb_AVDq8B_B48Z8r2sszS1GeWSpry-QyZrS3cSomasQK_2IM-gZPASjjOA4FBQUoKSnBqVOnEAwGUVJSgjNnzgBAhBDyvFw6uhMAAOy6-AEa8z-PFdnKI3aH0Y6HXc142NUMAAiIgdj7ATgTbIZcGEhytzYmjOPH536eUvl6g33oDfZhUdbClK4DYi-lSEcAOaIFqwM1WOlfggxqAsdxZU6nE2VlZSCEoLOzE0ajEatWrUJPT2J18-sNDQ2y26l1NwYAYq3Ac6e_r7iBQw4zb0ZxRiHyjfaknR-WIvh2zwsYiV5MuYw_GXg95WsAIJs3p34RBRaGi9HkqcPjQw9h7cQKZBssKC0txdq1a1FdXY1oNIo9e_bAarVi9erVAACPxwMAUUmSZGs_oNMWAABGoxfxzVPfwfOV31Ltu2fKmDCOZ3tfvGo3cLIcGD-EF_v-DV8v-2vFF0_IkcrOI1ckH0tDFVgSWoQc0QIAsFgsKC4uRkFBAXg-lu_Q0BA6OjqwfPlyLFwYa5UGBgbiff9_bt68-bRSHroVAACcDp7FV048jScXfBkb827XNO1_6nkeR_2fpZVG2-h7-GTiUzzkbMI66y0oMjllzwuIQfSHB3A62A-v4FNNsyBqx9LQIiwJVsAqxmIKhBA48h0oLi6G1Wq94vwTJ07g6NGjuO222-B0xvKnlGJoaAgABADfVcsv7eeVugMPzMlmt-XZS7HV2YzbrLck3cSr8b5nL547_ZIGJbuMzZCLfKMD2YZYM-8VfBgXfKrT2AQErqgDlaEyLA5WwC5edrDFYoHT6YTT6YTJdPUiln379sHtduOOO-64QhgejwfHjh0DpfSNpqYm5dEqdN4CTKZ74ji6J44jm7dgTe7NqLEsRlVWBZymfBSYHDBOWjYmUAFDkRGIVEKpwnazjXm3Y8doO_aPH5S1z4QxYTyp6WQDNaAsXITKcBkWhUuRLV4eF2RmZiI_Px9OpxMWi0X2ekmSsHv3bgiCgE2bNiEz88rw86XaDwDTKnzetADJkMllXLG0zGG04_WaH8KsMPC6EBnCXx3926TjCelgFbKxMFKCRaFSlEdKwNNY_00IgcViQV5eHvLz8xNOV3rVTDgcxs6dO5GTk4P169fDaLxyfWM0GkVXVxcope81NjbeM1255k0LkAxT1xWORi_iFxfexN8seFT2_CKTE48UPoRXz_9S87IQEDijDiwKlaIyXApX9PJA1mg0IicnBzabDXa7HUajEYQQEEJAKVV0vs_nw44dO1BRUYGVK1eC47j4QC9xjdvtjqfxYjLlvK4EIMf24bdxr-MuVGVVyNq3ujZjt-eP6AmeSTsvjnKoiCzA4mA5KsNlyJBi_TYhBLnWXFitVuTm5sJsNiccniyDg4Nob2_HypUrUV1dDQAJ58eRJAkXLlwAgE_r6-t_n0y6170AJCrh-2dfwY-XPC8bDeQJj2-UPYGvnnhmxiFah2DDysAS1ASqkEljO5x4nofVboXVGvszGGJf9WSnT63tk48n_7-npwednZ2ora2Fy-W6yvHx84eHhxGNRkEpfYkQktTNXPcCAGLrDN4Z3Y16xyZZ-zJLNerzN-HtkV0ppVsScWHDxGosDMcGmvGanpeXB5vNlqjlck17ss4_dOgQPvvsM9TV1SE3N1fW-XEGBwcB4ALP828kew83hAAA4NWBX-IO6zrF-foHnU14Z3R3Uu_wyROs2DS-IeF4s9kMu90Om80GnuenbdqTcb4kSejo6MDQ0FBipD_V-ZOv83q9CAQCIIT8qL6-PulR7Q0jAK8wjlfP_wp_V_bEFZ9fCLuxffhttI7snNb5BARr_Stwu281eMrDYrHA5XJd1acnW7uVbNFoFB988AEopairq4PRaEw4X2mQeKn2T1BKX0nle7lhBAAAbSO7cL-jDjWWJTgVPI3fuluxy_NBUrWepzzu9daiJlgFjuPgKnTBbr96eXm6zg-FQmhvb4fNZsOKFSuuGOkr4ff7MT4-DgA_a2xsTGnzxA0lAAqKF_t-gjyjLenlX0Cs5t8_9jksCVXAaDSirKwMGRlXb2dP1_lerxd79uxBWVkZqqurE2MHtUdDSinOnz8PACKAf036pi5xQwkAAM6E-nEm1J_SNRt8q7EkVAGe51FaWpoIy6bqYDWb2-3GRx99hJtuugnFxcUJmxyTr59U-99sbGzsTenGcAMKIFXyhTysn1gJAFiwYMGsOL-3txeHDx_GunXrYLVap631k7nU91OlBR_TwQQwDfd4bwcHDg6HIxFz18r5ANDd3Y3-_n7U1tYiKysrqVofJxAIwOfzgRDyfw0NDcn3aZNgAlBhQaQQJREXjEYjHI7Yr45o5XxRFNHZ2Qmfz4cNGzbAYDBAkqSko4OU0njUD6Ioqk75qsEEoMIqf2xJWl5eHgDtnB-JRLB3714YjUasX78ePM8rRveUBOH1euH3-wHg95s3b1Z-Bfo0MAEoYKJGVIXLwPN8IgKnhfP9fj_27t0Ll8uFRYsWJUb6cudPZXKQyO12X_ro6qXeqTC_ft5iDmltbX0IwJu5ublwOp1XBHomh3gnH09nGx0dxf79-7F48WIUFl7eoDrV4ZOP5WzDw8MYGRkBgF83Njb-WTr3yVoABSil98bn6id9NuOa39_fj-7ubtx8881XxfSTqfVxBEHA6OgoAIR4nn8m3ftkAlCA47h1AGRH_lOPp7MdP34c586dw7p162AymaaN7KkJYnBwMG7_wf33339m5ncYgwlAhvb29ky_319jMpkSodiZOF8URRw8eBDBYBC33norDAbDtDF9NXw-HyYmJgDATQh5Ib27jMEEIEMwGFwEwBCvrTNxfjQaxb59-5CRkZFUTH-6bkAUxcRaP0LI1-vr6zV5lw0TgAySJFUASCziiJNsXx0MBtHR0YHCwkKUlJQk7KnU-qnnDg0NxeME_9vQ0PDfqd-VPEwA8hQCSGy8AJIfA3g8HnR1daGqqgp2u101uJOsIMbHxxEIBADALQjCE9OdnwpMADIQQuwzee4fGBjA8ePHUVNTA4vFknJwR84WiURw8eJFAJAIIV9qbm52a3CLCZgAZJAkyRJ_fk_G-ZRSnDx5Em63G8uXL09qpJ8M8X7_UlrfaWho2Jl2olNgAlBham1Ucv4nn3wCQRCwbNky2bBuqrU-_vnw8DAEQQCA7V1dXWlF_JRgAlBhupovCAK6urpgNptRWVmZ1OqdqWkp2UZHRxEOhwGgi1L6pW3bts3Ke-yZAFQQRRGAvPODwSAOHDiAwsJC5OfnJ2xxZjrip5TC6_UiGAwCwElRFBubm5sD2t3VlTAByEAIEYHLAogTd5TH40F3dzfKy8uRk5OTVHAnGUFQSuHxeOI1v08QhE1btmzRdNA3FSYAGSilHqVZusHBQfT29qK6ujqtwZ5cjH9sbCze5x8lhNRv2bIltbVrM4AJQAZCyAiAuDMSnD17FsPDw6iurk4M9tKt9UBsZY_f74-LaS-ltLmxsVH51y01hAlAnhEg9gwOxBzZ09ODcDiMsrIy1cFeKoIIh8MIBAJxoQkAvhcIBJ7dunXrnP1sCROAPANALJ4viiL6-vogSRJcLldiQUaqEzlxKKUIh8MIh8OTW5gjlNLHm5qa9mtU_qRhApCB47heSZJESinf398Pg8GA3NzYr4ykGt2TJAmUUkSjUUSj0andymkALwQCgde2bt0qyiYwy7AVQQq0trb2AqiIH3McB47jEit8OO7yC9YmP8LF_yRJgiiKcoKJAmijlL4WDAbbrpXj47AWQAFCyHcppU0A1gAoliQJkjTjWEwfgPcJIe8SQnbW19dr91PoacJagCTYsWNHUTQareQ4rgLAQkppMSEkk1KafenfLAAUwBghZIJS2g9ggOO4U5IkfZzqfj0Gg8FgMBgMBoPBYDBmif8HWTKhDmbR-TYAAAAASUVORK5CYII%3D"

- name: QtCreator - Make sure that the config directory exists
  file:
    path: "{{homedir}}/.config/QtProject/"
    state: directory
    recurse: yes
- name: QtCreator - Copy config file
  copy:
    src: QtCreator.ini
    dest: "{{homedir}}/.config/QtProject/QtCreator.ini"
    force: no
- name: QtCreator - Configure Plugins (Category)
  lineinfile:
    destfile: "{{homedir}}/.config/QtProject/QtCreator.ini"
    line: "[Plugins]"
- name: QtCreator - Configure Plugins (Enable)
  lineinfile:
    destfile: "{{homedir}}/.config/QtProject/QtCreator.ini"
    regexp: '^ForceEnabled='
    insertafter: "[Plugins]"
    line: "ForceEnabled=BareMetal, ClangCodeModel, ClangRefactoring, Todo"
- name: QtCreator - Configure Plugins (Disable)
  lineinfile:
    destfile: "{{homedir}}/.config/QtProject/QtCreator.ini"
    regexp: '^Ignored='
    insertafter: "[Plugins]"
    line: "Ignored=Bazaar, CVS, Mercurial, Perforce, QbsProjectManager, Qnx"
- name: QtCreator - Set projects directory
  lineinfile:
    destfile: "{{homedir}}/.config/QtProject/QtCreator.ini"
    regexp: '^Projects='
    insertafter: "[Directories]"
    line: "Projects={{homedir}}/src"
- name: QtCreator - Set template for build directory
  lineinfile:
    destfile: "{{homedir}}/.config/QtProject/QtCreator.ini"
    regexp: '^BuildDirectory.Template='
    insertafter: "[Directories]"
    line: "BuildDirectory.Template={{homedir}}/build/%{JS: Util.asciify(\\\"%{CurrentProject:Name}-%{CurrentKit:FileSystemName}-%{CurrentBuild:Name}\\\")}"
- name: QtCreator - Copy device configurations
  template:
    src: qtcreator/devices.xml
    dest: "{{homedir}}/.config/QtProject/qtcreator/devices.xml"
    owner: vagrant
    group: vagrant
    mode: 0644
