---
- name: Clone the Qt source repository
  git:
    repo: 'git://code.qt.io/qt/qt5.git'
    dest: "{{ toolsdir }}/qt5-src"
    version: "v{{ qt_version_major }}.{{ qt_version_minor }}"
    force: yes

- name: Install mesa development headers (for Qt gui development)
  apt:
    name: ['mesa-common-dev', 'libgl1-mesa-dev']
    state: present
  become: true

- name: Install aditional development packages for compiling Qt
  apt:
    name: ['libfontconfig1-dev', 'libfreetype6-dev', 'libx11-dev', 'libxext-dev', 'libxfixes-dev', 'libxi-dev', 'libxrender-dev', 'libxcb1-dev',
           'libx11-xcb-dev', 'libxcb-glx0-dev', 'libxkbcommon-x11-dev', 'libxcb-keysyms1-dev', 'libxcb-image0-dev', 'libxcb-shm0-dev', 'libxcb-icccm4-dev',
           'libxcb-sync0-dev', 'libxcb-xfixes0-dev', 'libxcb-shape0-dev', 'libxcb-randr0-dev', 'libxcb-render-util0-dev', 'libssl-dev']
    state: present
  become: true

- name: Copy Qt host compilation script
  template: src={{ item }} dest=/usr/local/bin/ mode=0755
  with_items:
    - host-compile-qt.sh
  become: true

- name: Create directory for Qt
  file: path="{{ toolsdir }}/qt-{{ qt_version_full }}/x86_64/" state=directory owner="{{ user }}" group="{{ user }}"

- name: Download and extract Qt
  unarchive:
    src: "http://soracum.cerritus.eu/qt-{{ qt_version_full }}-x86_64.tbz2"
    dest: "{{ toolsdir }}/qt-{{ qt_version_full }}/x86_64/"
    creates: "{{ toolsdir }}/qt-{{ qt_version_full }}/x86_64/bin"
    remote_src: yes

- name: Install Qt Creator
  apt:
    name: ['qtcreator']
    state: present
    install_recommends: no
  become: true

- lineinfile:
    destfile: "{{ homedir }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    line: '[Containments][2][Applets][3][Configuration][General]'

- name: Set the favorites for the start menu
  lineinfile:
    destfile: "{{ homedir }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    insertafter: '^[Containments][2][Applets][3][Configuration][General]'
    regexp: '^favorites=preferred://.*'
    line: 'favorites=preferred://browser,org.kde.dolphin.desktop,org.kde.kate.desktop,DigiaQt-qtcreator-community.desktop,systemsettings.desktop'

- lineinfile:
    destfile: "{{ homedir }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    line: '[Containments][2][Applets][5][Configuration][General]'

- name: QtCreator - Make sure that the config directory exists
  file:
    path: "{{ homedir }}/.config/QtProject/"
    state: directory
    recurse: yes
- name: QtCreator - Copy config file
  copy:
    src: QtCreator.ini
    dest: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    force: no
- name: QtCreator - Configure Plugins (Category)
  lineinfile:
    destfile: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    line: "[Plugins]"
- name: QtCreator - Configure Plugins (Enable)
  lineinfile:
    destfile: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    regexp: '^ForceEnabled='
    insertafter: "[Plugins]"
    line: "ForceEnabled=BareMetal, ClangCodeModel, ClangRefactoring, Todo"
- name: QtCreator - Configure Plugins (Disable)
  lineinfile:
    destfile: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    regexp: '^Ignored='
    insertafter: "[Plugins]"
    line: "Ignored=Bazaar, CVS, Mercurial, Perforce, QbsProjectManager, Qnx"
- name: QtCreator - Set projects directory
  lineinfile:
    destfile: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    regexp: '^Projects='
    insertafter: "[Directories]"
    line: "Projects={{ homedir }}/src"
- name: QtCreator - Set template for build directory
  lineinfile:
    destfile: "{{ homedir }}/.config/QtProject/QtCreator.ini"
    regexp: '^BuildDirectory.Template='
    insertafter: "[Directories]"
    line: "BuildDirectory.Template={{ homedir }}/build/%{JS: Util.asciify(\\\"%{CurrentProject:Name}-%{CurrentKit:FileSystemName}-%{CurrentBuild:Name}\\\")}"

- name: Download the linuxdeployqt AppImage
  get_url:
    url: https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    dest: /usr/local/bin/linuxdeployqt
    mode: 0755
  become: true
