---
- name: Install additional mesa development headers (for Qt gui development)
  apt:
    name: ['libgles2-mesa-dev']
    state: present
  become: true

- name: Copy Qt cross compilation scripts
  template: src={{item}} dest=/usr/local/bin/ mode=0755
  with_items:
    - cross-compile-qt.sh
    - qt-sync.sh
  become: true

- name: Create directories for the Raspberry Pi sysroot and Qt
  file: path="{{toolsdir}}/raspberrypi-qt/{{item}}" state=directory owner="{{user}}" group="{{user}}"
  with_items:
    - qt5
    - qt5pi

- name: Download and extract Raspberry Pi sysroot
  unarchive:
    src: http://soracum.cerritus.eu/raspi_sysroot.tbz2
    dest: "{{toolsdir}}/raspberrypi-qt/sysroot/"
    creates: "{{toolsdir}}/raspberrypi-qt/sysroot/lib"
    remote_src: yes

- name: Download and extract Qt host tools for the Raspberry Pi
  unarchive:
    src: "http://soracum.cerritus.eu/raspi_host_qt-{{qt_version_full}}.tbz2"
    dest: "{{toolsdir}}/raspberrypi-qt/qt5/"
    creates: "{{toolsdir}}/raspberrypi-qt/qt5/bin"
    remote_src: yes

- name: Download and extract Qt for the Raspberry Pi
  unarchive:
    src: "http://soracum.cerritus.eu/raspi_qt-{{qt_version_full}}.tbz2"
    dest: "{{toolsdir}}/raspberrypi-qt/qt5pi/"
    creates: "{{toolsdir}}/raspberrypi-qt/qt5pi/bin"
    remote_src: yes

- name: QtCreator - Copy configurations configurations
  template:
    src: "qtcreator/{{item}}"
    dest: "{{homedir}}/.config/QtProject/qtcreator/{{item}}"
    owner: vagrant
    group: vagrant
    mode: 0644
  with_items:
  - devices.xml
  - debuggers.xml
  - toolchains.xml
  - profiles.xml
  - qtversion.xml
